### ISSUE TITLE
Received unexpected payload: ............"part_armed_1"}

### ISSUE THREAD

**Issue by MikeLDPT** [dchesterton/texecom2mqtt-hassio#20]
Hi,

**Describe the bug**
I have noticed that when I Arm or Part Arm the alarm, I am seeing an error in the log, for e.g.  :

Logger: homeassistant.components.mqtt.alarm_control_panel
Source: components/mqtt/alarm_control_panel.py:172
Integration: MQTT (documentation, issues) 

Received unexpected payload: {"id":"A","name":"xxxxxxxxxxxx","number":1,"status":"part_armed_1"}

The status of the alarm in HA then remains as "Pending" rather than "Part Armed" or "Armed" until it is next turned off.  Is there something that I can do to correct this please?

**Application version** 1.0.39, just upgrading to 1.0.40

**Texecom alarm type**
Premier Elite 64

**Comment by dchesterton** [comment]
Hi Mike, this sounds like an issue with your configuration and your mapping. Please can you post your full config and I can look into it more?

**Comment by MikeLDPT** [comment]
Hi,

Thanks for the reply.  The texecom2mqtt configuration isn't very long and is as follows (I have of course disguised the security details:

texecom:
  host: 192.168.0.nn
  udl_password: 'nnnn'
mqtt:
  host: core-mosquitto
  username: MQTT
  password: XXXXXXXXX
homeassistant:
  discovery: true
areas: []
zones: []

Unfortunately things have gone from not particulary concerning to rather bad.  I haven't looked around HA for quite a while, and as you can see I managed to look at the texecom2mqtt configuration in Supervisor.  I then started to find out if there was any information in logs or maps or history for texecom2MQTT, and it seems it has not recirded anything for many days.  When I tried to relook at the Texecom2MQTT log in Supervisor, I find that Supervisor is  is locked out: a blank screen with circle whizzing round but never loading the Supervisor page. Restarting HA doesn't cure it.

Unfortuanately I cannot give you any more information at this time therefore.

Anyway, if there is anything wrong in the configuration then  please let me know.

Many thanks,

**Comment by MikeLDPT** [comment]
Hi again Daniel.  I have access to Supervisor back, and have updated to Version 1.0.41.

The log suggests an issue which you will be able to interpret:

2021-05-16 15:03:11 - INFO: Starting texecom2mqtt v1.0.41...
2021-05-16 15:03:11 - INFO: Connected to alarm, sleeping for 1 second...
2021-05-16 15:03:12 - INFO: Connection ready
2021-05-16 15:03:30 - ERROR: Unhandled rejection - Command serial timed out 5 times and could not be completed

I rebooted the Raspberry Pi just after 14:20 and went out just after 14:30, returning shortly after 15:00.  Note that the alarm remained "pending" rather than "armed" 16:03 is when I updated to 1.0.41.   The logger records the fact that the "full_armed" event was an "Unexpected Payload": 

```
Logger: homeassistant.components.mqtt.alarm_control_panel
Source: components/mqtt/alarm_control_panel.py:157
Integration: MQTT (documentation, issues)
First occurred: 15:10:05 (1 occurrences)
Last logged: 15:10:05
Received unexpected payload: {"id":"A","name":"XXXXXXXXXXXXX","number":1,"status":"full_armed"}

```

I cannot match the "First occurred: 15:10:05 " to the events in the logbook

HOWEVER:  I have also noted this error in the log:

`First occurred: 15:10:05 (1 occurrences)
Last logged: 15:10:05
Template variable warning: 'dict object' has no attribute 'full_armed' when rendering '{% set values = {"in_entry":"pending","in_exit":"pending","disarmed":"disarmed","triggered":"triggered"} %}{{ values[value_json.status] }}'`

Maybe that is the best clue as yet to the problem?

The logbook records: 

XXXXXXXXXXXXXXX became unavailable
16:03:07 - 13 minutes ago
XXXXXXXXXXXXXXX changed to Disarmed
15:11:07 - 1 hour ago
XXXXXXXXXXXXXXX became unavailable
15:07:50 - 1 hour ago
XXXXXXXXXXXXXXX changed to Disarmed
15:04:30 - 1 hour ago
XXXXXXXXXXXXXXX changed to Pending
14:32:29 - 2 hours ago
XXXXXXXXXXXXXXX changed to Disarmed
14:31:20 - 2 hours ago
XXXXXXXXXXXXXXX changed to Disarmed
14:24:13 - 2 hours ago
XXXXXXXXXXXXXXX became unavailable
14:23:50 - 2 hours ago

At this time ALL texecom devices are indicated as unavailable, and that seems to be just after the upgrade to 1.0.41.  Ooops :-) I have re-discovered that texecom2mqtt does not restart automatically after upgrade.  The minimal log entries which I thought showed an error condition may just be reflecting that fact therefore? Now restarted, and log looks good.  Panel, Areas and zones all "fetched" and "application ready"!

Thanks again.

**Comment by MikeLDPT** [comment]
Hi again Daniel.  I'm floundering a bit here.  Since upgrade every, whilst the texecom2mqtt seems to start correctly, I am seeing this type of message for all sensors:

`2021-05-17 19:40:28 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform mqtt does not generate unique IDs. ID 1700430.zone.lounge already exists - ignoring binary_sensor.lounge`

I thought I'd better mention it sooner rather than later in case its connected to my other issue. 

Pointers ion how to correct this one would be appreciated. 

Thanks,
Mike

**Comment by dchesterton** [comment]
Hi Mike,

Can you pull down the latest version? 1.0.42? There were a couple of bugs in 1.0.41 which I think you've encountered.

As for your original error, you need to map your areas to the Texecom arm types, e.g.

```
areas:
  - id: A
    full_arm: armed_away
    part_arm_1: armed_night
    part_arm_2: armed_home
```

**Comment by MikeLDPT** [comment]
Hi Daniel,

Thanks.  1.0.42 has sorted out the non-unique IDs and entities are back to available.

I will work on updating the config.....  I'm afraid I must have been being a bit lazy, and on seeing "optional" in the doc, I didn't look any further.

Many thanks for your help.
Mike

**Comment by MikeLDPT** [comment]
Hi Daniel,

I'm afraid I'm struggling a bit with this.  I have added the Areas data and Zones data in the config now.  The Zones data is working in that I have a door symbol for the ones now defined as a door. But I can't seem to make the areas entries work.  I still get the error mentioned above as in:

`Received unexpected payload: {"id":"A","name":"XXXXXXXXXXXXX","number":1,"status":"full_armed"}`

The relevant bit of the config is now as below, and I have tried many versions to try to get the desired outcome:

```
.
.
homeassistant:
  discovery: true
areas:
  - id: A
    name: nn_xxxxxxxx_xxxx
    full_armed: armed_away
    part_armed_1: armed_night
    part_armed_2: armed_home
    in_entry: pending
    in_exit: pending
    disarmed: disarmed
    triggered: triggered
zones:
  - id: kitchen_doors
    device_class: door
  - id: lounge_doors
    device_class: door
  - id: ground_flr_bed
    device_class: door
``` 

I notice that the Texecom debug info doesn't contain the new area status's I placed in the config... is that helpful in understanding and resolving this?

![image](https://user-images.githubusercontent.com/70011875/119239595-0ae5cc80-bb42-11eb-9d69-cdf812effc74.png)

If there is any more help that you can give me, I'd appreciate it.

Thanks,
Mike

**Comment by MikeLDPT** [comment]
I've finally made this one work now.  Appologies that it has taken so long. Hard one to admit, but I didn't notice that I was using full_arm**ed** and you were suggesting full_arm (etc.).  Cross checked so many times and didn't spot it
